### ISSUE TITLE
Documentation publishing job

### ISSUE THREAD

**Issue by mcdoker18** [odahu/odahu-docs#14]
Subj needs to be created.
It have to:
- build documentation artifacts on every commit (PR, for example) that should be public
- publish built HTML static files to [docs.odahu.org](https://github.com/odahu/docs.odahu.org) repo after every comit to `develop` branch

**Comment by mcdoker18** [comment]
Moved to the cicd

**Comment by maxkochubey** [comment]
Reopened after discussion with @dsuslov. We should try Github Actions for this.
