### ISSUE TITLE
Odahu-flow cluster consumption

### ISSUE THREAD

**Issue by mcdoker18** [odahu/odahu-docs#34]
We should determine a Odahu-flow cluster consumption of resources(cpu, memoty) and money for:

- [ ] GKE (@karbyshevds @maxkochubey )
- [ ] EKS (@karbyshevds )
- [ ] AKS (@maxkochubey )

As result of investigation, we should create the new section in the documentation.

**Comment by dsuslov** [comment]
obsolete
